modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="classicskies"
version="1.0.0"
displayName="Classic Skies"
credits="Majority of the textures are by Mojang"
displayURL="https://curseforge.com"
authors="sonicSnap"

[[dependencies.classicskies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




